### ISSUE TITLE
failing  converting/from to neanderthal matrices in latets neanderthal 0.49.1

### ISSUE THREAD

**Issue by behrica** [cnuernber/dtype-next#100]
see here:
https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/convert.20neanderthal.20matrix.20to.20dataset.20.3F

**Comment by jsa-aerial** [comment]
@cnuernber When you say "I need another Neanderthal namespace for latest", does this mean there would need to be two such namespaces - one for pre 49 and one for 49+?  Also, is this likely to be done anytime soonish?  I will need to stay on 48 for some things until this is ready.  Many Thanks!

**Comment by cnuernber** [comment]
Well what I want is for things to just work so creating two namespaces and moving existing code to the 48-and-previous namespace and creating new code for the 49 namespace and then the existing neanderthal namespace just tries one and then the other for its actual implementation.

**Comment by jsa-aerial** [comment]
Ah, gotcha.  NIce way to go.
