### ISSUE TITLE
Reading and writing array fields in structs

### ISSUE THREAD

**Issue by phronmophobic** [cnuernber/dtype-next#108]
I'm working with a struct with fields defined like:
```c
struct ggml_tensor {
        ...
        int64_t ne[GGML_MAX_DIMS];
        ...
}
```
Full definition [here](https://github.com/ggerganov/ggml/blob/ea40f60c22ce4f5066fbb21e8c825d828e84c529/include/ggml.h#L600).

It seems like I can define the struct just fine:
```c
(dt-struct/define-datatype!
  :ggml_tensor
  [...
   {:name :ne  :datatype :int64 :n-elems 4}
   ...])
```
However, I'm not sure if there's a straightforward way to read and write to the array.
```clojure
> (dt-struct/define-datatype! :example [{:name :x :datatype :float32 :n-elems 10}])
...
> (def my-example (dt-struct/new-struct :example ))
#'com.phronemophobic.ggml.impl.raw/my-example
> my-example
{:x 0.0}
> (:x my-example)
0.0
> (.put my-example :x (dtype/->long-array (range 10)))
Execution error (ClassCastException) at ham_fisted.Casts/doubleCast (Casts.java:117).
class [J cannot be cast to class java.lang.Number ([J and java.lang.Number are in module java.base of loader 'bootstrap')
```

It's not a huge deal since it seems like I can work around it with the advice from the [ffi docs](https://cnuernber.github.io/dtype-next/tech.v3.datatype.ffi.html).

> It is possible with older creakier libraries you will need to pass in the address to struct members. This [happened a lot in avclj](https://github.com/cnuernber/avclj/blob/master/src/avclj.clj#L266).

**Comment by cnuernber** [comment]
Could you try this change out and see what you think?  Honestly getting the member ptr, creating a native buffer of the desired type should all work fine and probably would be faster but now it is supported at a basic level (dtype functions such as copy!, sub-buffer etc work on the member value).

**Comment by phronmophobic** [comment]
Ok, I'll try to give a try soon and report back. Thanks!

**Comment by phronmophobic** [comment]
Everything seems to be working!
