### ISSUE TITLE
Typo in overview docs example?

### ISSUE THREAD

**Issue by phronmophobic** [cnuernber/dtype-next#118]
There's some example output [here](https://github.com/cnuernber/dtype-next/blob/6a5da39a51e211055b507fd4d77e35cb9d3b7a8f/topics/overview.md?plain=1#L246) that seems to either be extraneous or missing the expression that would generate the value.

**Comment by harold** [comment]
Agreed - that looks odd, thanks for the report.

The whole file looks like it could use some love. (:

**Comment by harold** [comment]
Some small improvements: https://github.com/cnuernber/dtype-next/commit/65928258758744817a9a73fcf065d24eb06cf2e6

@phronmophobic - any other ideas about how this could be improved or reorganized or expanded?

What part of this is interesting to you?

**Comment by phronmophobic** [comment]
I've wrapped several native libraries. Previously, I used JNA because dtype-next's ffi didn't support passing structs by value, but I recently starting trying dtype-next since that limitation has been addressed. I'm excited to use dtype-next since it's already integrated with the ecosystem and has an expressive library for manipulating data on the native heap.

Currently, my goal is to train a neural network and potentially run inference on some existing models by [wrapping](https://github.com/phronmophobic/ggml.clj) a native library called [ggml](https://github.com/ggerganov/ggml).

Some of the areas I would be interested or more ffi related, but here are some thoughts off the top of my head based on my usage so far:

Most of the time, I start with translating either some c, c++, or python code into the equivalent clojure code. Part of this is certainly part just learning the library, but I still often struggle to map some operation onto some dtype-next code. I've read the overview and the cheatsheet, but I still don't really know where to begin looking when I want to accomplish some specific task. This is probably a bit more specific to doing ffi with dtype next, but there are several related namespaces (datatype, datatype/ffi, datatype/struct, datatype/protocols, datatype/native-buffer) and I'm never sure where to start. Additionally, it seems like sometimes I need to use java interop to accomplish my goal (eg. `(.put struct k v)`). This is especially true for writing data. Making small changes to native data isn't very common for data sciency things, but it's common for ffi use cases to receive some native data that needs to be tweaked in some small way.

As an example, I wanted to transpose a matrix which is represented as a tensor. `tranpose` was in `datatype.tensor`. `transpose` requires `reorder-indexes`. I found `tensor->dimensions` in the `datatype.tensor` namespace, but I eventually went with `dtype/shape`, but after more searching, I eventually found `.rank` in the NDBuffer interface (which doesn't seem to have a clojure equivalent).

-----

There are several types and it's not really clear what roles each plays. `dtype/make-container` seems to return a buffer. Does it always return a buffer? Some of the documentation refers to containers and some to buffers. Is there a distinction? Further, there are also readers and writers which seem related to buffers. Are buffers readers? Are readers buffers? Can a reader be a writer? There are methods for `->buffer` and `->reader`. Why would I use `->reader`? There's also tensors and buffers. It seems like tensors can be multi dimensional while buffers are 1d. Is there a difference between a 1d tensor and buffer? Why?

---

Since I'm working with native libraries, it's necessary for me to know which operations actually change data in memory vs which operations just provide a new view of the data without actually writing to memory. 

What does "in-place" mean?
> transpose: In-place transpose an n-d object into a new shape. Returns a tensor.

My understanding of "in-place" is that it typically means mutating data vs performing an operation and returning a new copy, but that doesn't seem to be the case for at least this example:
```clojure
> tensor
#tech.v3.tensor<int64>[3 2 3]
[[[1 2 3]
  [1 2 3]]
 [[1 2 3]
  [1 2 3]]
 [[1 2 3]
  [1 2 3]]]
> (dtt/transpose tensor [2 1 0])
#tech.v3.tensor<int64>[3 2 3]
[[[1 1 1]
  [1 1 1]]
 [[2 2 2]
  [2 2 2]]
 [[3 3 3]
  [3 3 3]]]
> tensor
#tech.v3.tensor<int64>[3 2 3]
[[[1 2 3]
  [1 2 3]]
 [[1 2 3]
  [1 2 3]]
 [[1 2 3]
  [1 2 3]]]
```

------

The overview and cheatsheet docs list several useful functions (eg. `emap`, `->tensor`, `broadcast`, etc.). The docs don't list the arguments which is very helpful for getting a sense of what each function does without leaving the page.

-----

Overall, I've been happy with dtype-next and will continue to use it in more projects. I do think having a guide that helps provide a mental framework for mapping operations found in other similar frameworks to dtype's system would be helpful.

**Comment by cnuernber** [comment]
Thanks for the very thoughtful response - these are helpful.  

* Needing java interop for mutate-in-place operations - This matches clojure more generally and I often use java interop so for personally this seemed to be expected aside from aset.  Are you suggesting a 'put' method in the struct namespace or something like that?  
* make-container return value ambiguous - yes I think make-container returns the container specifically so the nativebuffer or the arraybuffer or base hamf array sublist when possible.  
* '->reader, ->writer' - If you want something that implements the Buffer interface then ->buffer is what we use now.  ->reader, ->writer should be deprecated really as they have proved to just be api noise - sorry for this confusion.  A Buffer is a java.util.List that supports long indexes and size (lsize) and some typed get/set operations (long, double) along with optimised reduce and parallel reduce operators.    
* A buffer and a 1D tensor are logically equivalent but a tensor specifically implements the NDBuffer interface which is overkill by far in contexts such as 99% of programs where tensors aren't necessary.  Tensors have a write pathway btw for typed double or long writes up to 3 dimensions.
* .dimensions - shape would have been fine for this - shape is a protocol and tensors (and other things) implement so I think I would just stick with dt/shape as it works with more types such as null.
* transpose and specifically the meaning of in-place - what I meant to say was transpose was a flyweight operation that simply puts a new addressing layer on top of the existing data buffer so it is O(1) regardless of size of the tensor and does no work - clone would make the transpose concrete.
* docs don't list arguments - this is I think a side effect of having multiple arity arguments to match the ND nature of the inputs but we could have more examples and such to make the argument usage much clearer. 

I am not sure there are other frameworks similar to dtype-next as it spans a space vertically but sparsely while e.g. tensorflow spans less of a vertical space and more of a horizontal space.  For the overlapping operations I agree it would be helpful and of course it is a large system and more docs especially perhaps a document describing the answers to your thoughtful questions and statements would doubtlessly be helpful.  

It has been very helpful that you have made several changes and PRs that have helped the library along in this regard and I think conversations like this the associated are the best way forward.

**Comment by harold** [comment]
That's neat that it's helpful to you from the ffi perspective - keep the great questions and suggestions for improvements coming.

**Comment by phronmophobic** [comment]
Most of the bullet points I listed are just symptoms and don't really articulate problems (or solutions). Many of them are just part of learning a new library, but hopefully it's helpful to capture the symptoms for further diagnosis.

As I'm thinking more about it, one of the problems is trying to map operations from c++ or pytorch to the equivalent in dtype-next. One option that might be helpful would be to have some good search tools. That's something that might be provided by dtype-next docs, but is probably better addressed by upgrading my IDE setup.

> Needing java interop for mutate-in-place operations - This matches clojure more generally and I often use java interop so for personally this seemed to be expected aside from aset. Are you suggesting a 'put' method in the struct namespace or something like that?

I think having clojure versions of functions can be helpful for finding the right function to call, but as mentioned, that's partially because I don't have a good IDE setup for doing java interop. Are there javadocs for the java parts of the dtype-next API?

> transpose and specifically the meaning of in-place

Ah ok. I guess in my head I was reading it as "mutate in-place".

Thanks again!
