### ISSUE TITLE
`tech.v3.libs.buffered-image/as-ubyte-tensor` seems to support only some image types

### ISSUE THREAD

**Issue by daslu** [cnuernber/dtype-next#126]
While `:ushort-565-rgb` does exist in [bufimg/image-types](https://github.com/cnuernber/dtype-next/blob/9170e69/src/tech/v3/libs/buffered_image.clj#L26), it is missing in [the relevant case clause](https://github.com/cnuernber/dtype-next/blob/9170e69/src/tech/v3/libs/buffered_image.clj#L266).

**Comment by daslu** [comment]
@phronmophobic explained to me ([zulip link](https://clojurians.zulipchat.com/#narrow/channel/151924-data-science/topic/clj-media.20with.20dtype-next.20-.20understanding.20pixel.20formats/near/490326990)) that it would not make sense for this image type.

**Comment by phronmophobic** [comment]
In theory, it could make sense to have a tensor that works directly with the `:ushort-565-rgb` format, but it's generally more straightforward to work with the already supported formats.

**Comment by daslu** [comment]
Thanks

**Comment by cnuernber** [comment]
It is missing because there are a ton of formats and I didn't support them all initially but I think in addition to supporting that type that case clause could be runtime extensible as opposed to how it is now.
