### ISSUE TITLE
Documentation for dt-ffi/define-library what are symbols?

### ISSUE THREAD

**Issue by davidpham87** [cnuernber/dtype-next#21]
Hello Cris,

I was wondering in the function `tech.v3.datatype.ffi /define-library`  what is the roles of the `symbols` argument? I tried to read the documentation, but I could not understand (I checked libpython-clj2 as well, still unable to reverse engineer xD).

Thanks a lot for the work, I love learning the lib.

Best regards,
David

**Comment by cnuernber** [comment]
Hey David.  Symbols are pointers defined in the shared library.  

The function definitions passed in all bind to symbols that are interpreted as functions but in addition you often want to bind to global pointers that define values.  In Python's case those are static structures and types such as PyNone or PyTrue.

So symbols are for global variables that aren't functions.  This isn't necessary when using REPL, you will just get warnings when you attempt to resolve a symbol that you haven't pre-declared.  For some compilation frameworks such as Graal Native you have to predeclare all the symbols you want access to.

**Comment by davidpham87** [comment]
Thanks a lot!
