### ISSUE TITLE
Unnecessary caveat on `tech.v3.datatype.ffi.graalvm/expose-clojure-functions`?

### ISSUE THREAD

**Issue by phronmophobic** [cnuernber/dtype-next#23]
> Another caveat - You cannot have any 'def,defonce' variables defined in your export
> file.  Any persistent state must be referenced also from your main class in your
> jarfile so it will have to reference systems used in your libfile.  'def', 'defonce'
> variables will show up as uninitialized exceptions at runtime when objects call
> into your library.

I don't think there's any restriction on using def or defonce variables in the library namespace. I was able to demonstrate two methods to avoid the unbound var issues in avclj.

For both methods, I added a dummy def and printed the value in `avclj.libavclj/initialize-avclj` like so:
```
(def my-str "hello")

(defn initialize-avclj
  []
  (println my-str)
  (libinit/initialize-avclj))
```

Without the following changes, it prints the unbound error as described in the caveat, but either fix correctly prints `"hello"`.
```
#object[clojure.lang.Var$Unbound 0x48fec7a3 Unbound: #'avclj.libavclj/my-str]
```

**Method #1: Update the `:main-class` to be the library namespace**
https://github.com/cnuernber/avclj/compare/master...phronmophobic:unbound-var-fix1?expand=1

If you change the `:main-class` for the uberjar from `avclj.main` to `avclj.libavclj`. The value "hello" is correctly printed.

**Method #2: Require the library namespace from the main-class**
https://github.com/cnuernber/avclj/compare/master...phronmophobic:unbound-var-fix2?expand=1

I added `avclj.libavclj` to the requires in `avclj.main` and that also fixed the unbound error.

------
I was also able to create a library that has shared state in the library namespace ([source](https://github.com/phronmophobic/mobiletest/blob/b845d2372a54c8f5730999330274289eb760c037/src/com/phronmophobic/mobiletest.clj#L17)). (btw, dtype-next worked like a charm for this project. Thanks!)

I _think_ the underlying issue is that even though the uberjar's main class isn't that meaningful when building a shared library, it's still used by `native-image` as a basis for pruning unnecessary classes. If the library namespace isn't either the main-class or required by the main class, then only the `defn`s are initialized.

**Comment by cnuernber** [comment]
Very nice!!  Great exploration and that is really helpful - I will update the docs in this area!

**Comment by phronmophobic** [comment]
I ran into the unbound var issue when trying to call a function required from another namespace in my library. Since I didn't have a main-class at all, the required function was unbound. Since avclj was a working example, I compared the setup with my library to narrow down the cause.
