### ISSUE TITLE
Unrecognized architectures always use 32 bits for pointers and size_t

### ISSUE THREAD

**Issue by phronmophobic** [cnuernber/dtype-next#30]
https://github.com/phronmophobic/dtype-next/blob/2f74026aa0840e781bd20fb917c5bc6a3aababda/src/tech/v3/datatype/ffi/size_t.clj#L12

I've been getting great use out of dtype-next targeting iOS (arm64). There's a few code paths that will silently convert pointers to 32 bits since `arm64` isn't recognized (eg. `(dt-ffi/make-ptr :pointer (.address ^Pointer (dt-ffi/->pointer arg))`).

I've fixed the specific missing architecture [here](https://github.com/phronmophobic/dtype-next/commit/2f74026aa0840e781bd20fb917c5bc6a3aababda#diff-0e51542dc45017500309d234eba4c4c59a4d9f3e055a0d8ef3eccbddb2f7757bR12).

I know it's a breaking change, but it may be worth throwing an exception if the architecture is unrecognized. Otherwise, it is very difficult to debug what the root cause is. An alternative that's less breaking would be to log a warning if the architecture isn't recognized and 32 bit is assumed.

**Comment by cnuernber** [comment]
You are right for sure.  Unrecognized arch should be exception else hard crash is very likely.
