### ISSUE TITLE
Make `dtype-next` compatible with `clj-easy/graal-build-time`

### ISSUE THREAD

**Issue by phronmophobic** [cnuernber/dtype-next#41]
From GraalVM 22 onwards, the `native-image global` `--initialize-at-build-time` option will be deprecated. This means you will have to list every package that you want to initialize at build time separately. `clj-easy/graal-build-time` will take care of this for you, but it does not work single segment namespaces like dtype-next's dependency, `primitive-math`.

I was discussing workarounds with @borkdude. Here are some options we came up with. If you like one, I would be happy to submit a pull-request.

1. Fork [primitive-math](https://github.com/ztellman/primitive-math), update the namespaces to have multiple segments, and replace the dependency with the fork.
2. Copy `primitive-math` into `dtype-next` with a multi-segment namespace.
3. I'm not totally sure how `graal-build-time` works, but I think it would be possible to add a class to `dtype-next` (see [here](https://github.com/clj-easy/graal-build-time/blob/9a7b5dc4a7d6599b146a2ae31f1d75b85b2613f7/src/clj_easy/graal_build_time/InitAtBuildTimeFeature.java)) that adds a setup step to initialize a hard coded list of `primitive-math` classes at build time.

**Comment by cnuernber** [comment]
Option #2 seems pretty straight forward :-).

**Comment by phronmophobic** [comment]
@cnuernber , Any preferences for the target namespace. Personally, I like to cleanly separate third party code, so I would probably put the code in `dtype-next/third-party/com/github/ztellman/primitive_math.clj` which would make the namespace `com.github.ztellman.primitive-math` and add `third-party` to the list of src paths. Happy to use whatever namespace convention you prefer though.

**Comment by cnuernber** [comment]
We don't currently have third party code like that so your suggestion for the very few libraries that we end up inheriting makes sense.  Let's go with it.

**Comment by phronmophobic** [comment]
Pull request [here](https://github.com/cnuernber/dtype-next/pull/43)

**Comment by cnuernber** [comment]
OK, now can we test with with `clj-build-easy`?  I will run through the various libraries such as tech.ml.dataset and make sure they use this namespace as opposed to primitive math.

Interestingly enough, I am not sure exactly which symbols in primitive math actually do perform better.  Back in the day it was most of them but the Clojure compiler has come a really long way and now there is some subset, the boolean operations I think, where it makes a big difference but the vast majority of these optimizations are done correctly if you have typehinted your stuff and have unboxed math setup.
