### ISSUE TITLE
Indicate required module cmd line if ops fail when running under JDK-17+

### ISSUE THREAD

**Issue by cnuernber** [cnuernber/dtype-next#50]
Operations that require creating a nio buffer of FFI support under JDK-17 will fail unless particular flags are provided which then add classes to the classpath.  We can indicate the required command line arguments in the exception thrown when these classes aren't present.

**Comment by behrica** [comment]
I am wondering if we have only 2 cases ?
< JDK 17
>= JDK-17

or more ?

**Comment by cnuernber** [comment]
Close - Before 16, =17.  16 is when they removed the unsafe method to construct a direct byte buffer from an integer.

**Comment by cnuernber** [comment]
This really isn't an issue as JDK-19 mainly works without these flags as the foreign module is not experimental any more.
