### ISSUE TITLE
How to convert array-of-structs   into  tech.v3.dataset?

### ISSUE THREAD

**Issue by zhaoyul** [cnuernber/dtype-next#51]
Is there a way to convert `tech.v3.datatype.struct` to `tech.v3.dataset`? 

I want to convert a binary block from ByteBuffer into a dataset, I convert it  all the way to array-of-structs, then  got stuck there.

Or should I bypass struct and convert array(reader) into dataset directly?

```
+----------------+
| NIO ByteBuffer |
+--------+-------+
         |
         |
+--------v-------+
|    ByteArray   |
+--------+-------+
         |
         | ->array-buffer ->  inplace-new-array-of-structs                                             
+--------v-------+                                            
| ArrayOfStructs |                                            
+--------+-------+                                            
         |  ????                                              
         |  how to do this? or there is a better convert path?
+--------v-------+
|  v3.dateset    |                
+----------------+
```

I defined the struct as the following:

```clojure
(dt-struct/define-datatype! :freq-fromat [{:name :field-strength :datatype :int16}
                                          {:name :gate-limit     :datatype :int16}
                                          {:name :occupy-rate    :datatype :uint16}
                                          {:name :average        :datatype :int16}
                                          {:name :max            :datatype :int16}
                                          {:name :min            :datatype :int16}])

(def x (dt-struct/inplace-new-array-of-structs
        :freq-fromat 
        (dtype/->array-buffer
         input-byte-array)))

;; x is a `datatype.struct.ArrayOfStructs` with 1936001 elements.

(count x)
;;=>1936001

(type x)
;; => tech.v3.datatype.struct.ArrayOfStructs

(take 2 x)
;; => ({:field-strength -206, :gate-limit 2000, :occupy-rate 0, :average 0, :max 1000, :min -1000}
;; {:field-strength -881, :gate-limit 2000, :occupy-rate 0, :average 0, :max 1000, :min -1000})
```

Thanks

**Comment by cnuernber** [comment]
This is a great question and I am really happy you asked that.  I haven't ported that pathway [over from v2](https://github.com/techascent/tech.datatype/blob/master/src/tech/v2/datatype/struct.clj#L572) yet but I will do so presently and report back.  I didn't know when anyone was going to get there so I wasn't going to put in the work until someone did -- now I am more than happy to put in some work :-).

**Comment by cnuernber** [comment]
* I [added a method](https://cnuernber.github.io/dtype-next/tech.v3.datatype.struct.html#var-column-map) in struct do get a map of columns from an array of structs.
* There is now a [unit test in dataset](https://github.com/techascent/tech.ml.dataset/blob/8da5dbbd4eb5a89297cf2c68bb4d97eadd381362/test/tech/v3/dataset_test.clj#L1381) that shows how to do this.

**Comment by cnuernber** [comment]
Closing this issue for now.  I really appreciate the issue and feel free to reopen if this doesn't work for you.

**Comment by zhaoyul** [comment]
Thanks Chris, 

I have tried, and It works like a charm.
