### ISSUE TITLE
`broadcast` --- some special cases and notes

### ISSUE THREAD

**Issue by harold** [cnuernber/dtype-next#54]
Here are some of my thoughts about broadcast from the last couple days:

1) Docstring typos "Broadcase":
 - https://github.com/cnuernber/dtype-next/blob/3da6abee81cc1b7a38d849a8ec5f2cc65053641f/src/tech/v3/tensor.clj#L67
 - https://github.com/cnuernber/dtype-next/blob/5008ddbaf696ae5d66172caa4331eeb643f8d64d/src/tech/v3/datatype/base.clj#L967
---

2) Trouble broadcasting up more than one dimension, at least in this case:

Got a tensor:

```clojure
> (dtt/ensure-tensor [1 2 3])
#<tech.v3.tensor_api.DirectTensor@26a4189e #tech.v3.tensor<object>[3]
[1 2 3]>
```

Up one dimension, no problem:

```clojure
> (-> (dtt/ensure-tensor [17 18 19 20])
      (dtt/broadcast [3 4]))
#<tech.v3.tensor_api.Tensor@2685e08f #tech.v3.tensor<object>[3 4]
[[17 18 19 20]
 [17 18 19 20]
 [17 18 19 20]]>
```

Up two dimensions raises an exception:

```clojure
> (-> (dtt/ensure-tensor [17 18 19 20])
      (dtt/broadcast [2 3 4]))
Execution error at tech.v3.datatype.index_algebra.IndexAlg/broadcast (index_algebra.clj:197).
Requested length 3 and base length 4 are not commensurate
```

But one at a time I can get the result I want:

```clojure
> (-> (dtt/ensure-tensor [17 18 19 20])
      (dtt/broadcast [3 4])
      (dtt/broadcast [2 3 4]))
#<tech.v3.tensor_api.Tensor@37156b1 #tech.v3.tensor<object>[2 3 4]
[[[17 18 19 20]
  [17 18 19 20]
  [17 18 19 20]]
 [[17 18 19 20]
  [17 18 19 20]
  [17 18 19 20]]]>
```

hth- thanks for this awesome lib, it's definitely helping me down the path I'm on at the moment.

![image](https://user-images.githubusercontent.com/7443/150852660-f12217cd-85f8-4ff0-94e7-fa8a6060ea1a.png)

**Comment by cnuernber** [comment]
Right- that is an issue.  Theoretically any shape can be extended at any point with a '1' and nothing about the actual data layout changes.  In this case the broadcast operator should be able to left-extend the source shape with '1's until it matches the target shape in length.

Great pic!

**Comment by cnuernber** [comment]
Fixed in 8.064

**Comment by harold** [comment]
Okay! This is working:

![image](https://user-images.githubusercontent.com/7443/151045094-917849ea-01c5-4d26-8e9b-cf965717cfbc.png)

Very cool.

https://user-images.githubusercontent.com/7443/151045166-1c81b938-9b81-4a58-95e3-38d3d9642154.mp4

**Comment by cnuernber** [comment]
Nice retro!  Did you literally do the raster yourself?

**Comment by harold** [comment]
I did. And with some new thoughts, as well.

Clojure is really a fun programming language.

Related: This gif made me realize how uptight might thinking had become:

![Pixel_vs_subpixel_precision](https://user-images.githubusercontent.com/7443/151058923-8744475b-ee7d-429e-9a6a-a000edc59269.gif)
