### ISSUE TITLE
Unexpected log message in simple program

### ISSUE THREAD

**Issue by harold** [cnuernber/dtype-next#55]
https://github.com/cnuernber/dtype-next/blob/2bf1eef6b5cefde3e3081e6e6577b6763116bae3/src/tech/v3/datatype/functional_api.clj#L204

I am seeing this output at the start of my program:

```
08:36:43.677 [main] DEBUG tech.v3.datatype.functional-api - JDK16 vector ops are not available: Syntax error compiling at (tech/v3/datatype/functional/vecopt.clj:1:1).
```

```
$ java -version
openjdk version "1.8.0_312"
OpenJDK Runtime Environment (build 1.8.0_312-8u312-b07-0ubuntu1~21.10-b07)
OpenJDK 64-Bit Server VM (build 25.312-b07, mixed mode)
```

I am on Java 8, so I don't expect to have JDK16 optimized vector operations.

Would it be possible to silence this log message until a time when it is more relevant? For example until later, when I explicitly try to benefit from these?

Thanks for your time and consideration.

**Comment by harold** [comment]
I have worked around this by setting the log level in `logback.xml` --- still perhaps good to consider if this message is helpful.

**Comment by cnuernber** [comment]
Yes it is and there is another one about insn being enabled/disabled.  The logback.xml silencing is actually necessary to get anything but horrid performance from parquet.  They literally log so much it drastically slows things down.

**Comment by cnuernber** [comment]
I may just disable the insn tensor indexing optimizations entirely as they don't help in most use cases and they cause a bit of a startup hit.

**Comment by harold** [comment]
Up to you - I've declared bankruptcy and am just blearing my eyes at all the noisy output for now.

**Comment by cnuernber** [comment]
Lol, well, I removed the log messages :-).
