### ISSUE TITLE
How do you use define-foreign-interface with GraalVM?

### ISSUE THREAD

**Issue by emassey0135** [cnuernber/dtype-next#59]
I am trying to pass a Clojure function as a callback in C, but I cannot figure out how to do this with GraalVM. I tried passing a class name to define-foreign-interface and importing the class, but even though the class file is generated during compilation and the import succeeds, trying to create an instance with a class makes the compilation fail. The approach in issue 28 does not seem the right way to do this because the generated function would have a extra parameter for a thread isolate, which would require writing a C wrapper function to create a thread isolate and pass it to the function, and including a separate dynamic library containing only such wrapper functions. Here is my code:

```clojure
(ns my-ns (:require
[tech.v3.datatype.ffi :as dt-ffi]
[tech.v3.datatype.ffi.size-t :as dt-size-t :refer [ptr-t-type]]
[tech.v3.datatype.struct :as dt-struct]
...)
(:import [tech.v3.datatype.ffi Pointer])
(:gen-class))
...
(def null (Pointer. 0))
(defn pointer->address [^Pointer pointer]
(.address pointer))
(defn string->utf-16 [str]
(dt-ffi/string->c str {:encoding :utf-16LE}))
(defn int->resource-value [n]
(Pointer. n))
...
(dt-struct/define-datatype! :window-class
[{:name :size :datatype :int32}
{:name :style :datatype :int32}
{:name :window-proc :datatype (ptr-t-type)}
{:name :class-extra :datatype :int32}
{:name :window-extra :datatype :int32}
{:name :instance-handle :datatype (ptr-t-type)}
{:name :icon-handle :datatype (ptr-t-type)}
{:name :cursor-handle :datatype (ptr-t-type)}
{:name :background-brush-handle :datatype (ptr-t-type)}
{:name :menu-name :datatype (ptr-t-type)}
{:name :class-name :datatype (ptr-t-type)}
{:name :small-icon-handle :datatype (ptr-t-type)}])
...
(def window-proc-interface (dt-ffi/define-foreign-interface :int64 [:pointer :int32 :int64 :int64] {:classname 'my-ns.window-proc-interface}))
(import my-ns.window-proc-interface)
(def window-proc-instances (atom []))
(def windows-api (dt-ffi/define-library-interface
{:CreateWindowExW {:rettype :pointer :argtypes [['dwExStyle :int32] ['lpClassName :pointer?] ['lpWindowName :pointer?] ['dwStyle :int32] ['X :int32] ['Y :int32] ['nWidth :int32] ['nHeight :int32] ['hWndParent :pointer?] ['hMenu :pointer?] ['hInstance :pointer] ['lpParam :pointer?]]}
:DefWindowProcW {:rettype :int64 :argtypes [['hWnd :pointer] ['uMsg :int32] ['wParam :int64] ['lParam :int64]]}
...
:RegisterClassExW {:rettype :int16 :argtypes [['WndClassEx :pointer]]}
...}))
...
(defn create-window [class-name & {:keys [window-name extended-styles styles x y width height parent-window-handle menu-handle parameter] :or {window-name null extended-styles [] styles [] x 0x80000000 y 0x80000000 width 0x80000000 height 0x80000000 parent-window-handle null menu-handle null parameter null}}]
(CreateWindowExW
...
(if (string? class-name) (string->utf-16 class-name) (int->resource-value class-name))
...))
(defn default-window-proc [window-handle message first-parameter second-parameter]
(DefWindowProcW window-handle message first-parameter second-parameter))
...
(defn register-class [name window-proc & {:keys [menu-name styles icon small-icon cursor class-extra window-extra] :or {menu-name null styles [] icon null small-icon null cursor null class-extra 0 window-extra 0}}]
(let [new-class (dt-struct/new-struct :window-class {:container-type :native-heap})
instance (window-proc-interface. window-proc)]
...
(swap! window-proc-instances conj instance)
(.put new-class :window-proc (pointer->address (dt-ffi/foreign-interface-instance->c window-proc-interface instance)))
...
(RegisterClassExW new-class)))
...
(defn window-proc [window-handle message first-parameter second-parameter]
(condp #(= message %)
(:close window-messages) (do (destroy-window window-handle) 0)
(:destroy window-messages) (do (post-quit-message 0) 0)
(default-window-proc window-handle message first-parameter second-parameter)))
(defn -main [& args]
(register-class "test" window-proc :icon (load-icon :application) :small-icon (load-icon :application) :cursor (load-cursor :arrow))
(let [window (create-window "test" :window-name "Test" :styles [:overlapped :caption :system-menu :thick-frame :minimize-box :maximize-box] :width 240 :height 120)
message (dt-struct/new-struct :message {:container-type :native-heap})]
(show-window window)
(update-window window)
(loop []
(if (> (get-message message null) 0)
(do (translate-message message)
(dispatch-message message)
(recur))
(:wparam message)))))
```

After compiling this code, there is a window-proc-interface.class file in the output directory for classes, but compilation fails with the following error:

```
class clojure.lang.Var cannot be cast to class java.lang.Class (clojure.lang.Var is in unnamed module of loader 'app'; java.lang.Class is in module java.base of loader 'bootstrap')
Execution error (ClassCastException) at user/eval155$fn (form-init16080142403006636056.clj:1).
class clojure.lang.Var cannot be cast to class java.lang.Class (clojure.lang.Var is in unnamed module of loader 'app'; java.lang.Class is in module java.base of loader 'bootstrap')
```

Line 155 of my file is:

```clojure
(defn window-proc [window-handle message first-parameter second-parameter]
```

**Comment by cnuernber** [comment]
Unfortunately all current GraalNative pathways that I have investigated required the extra parameter.  There was talk about graal native supporting the new foreign module but as of last time I checked it did not and additionally several of us looked at the truffle native interface and we couldn't figure out how to get a simple example working using it.

Callbacks back into native applications are an outstanding issue with the graal native compilation system.  Hopefully one of the two pathways above bears fruit sometime soon.

**Comment by emassey0135** [comment]
Okay, thanks for your response. I will try the Truffle Native Function Interface, and if that doesn't work, maybe I can do it with Libffi somehow, by interfacing with it using dtype-next, since the Truffle Native Function Interface uses Libffi internally. If the Truffle Native Function Interface works, it might be useful for other things besides callbacks, for example you could include SCI and bind to any native C function at the REPL without recompilation. Creating something based on Libffi would also make this possible.

**Comment by emassey0135** [comment]
Never mind, I found out that Libffi closures are not supported on iOS because Apple does not allow code generation at runtime, which the Truffle Native Function Interface probably also uses, and since I plan to support iOS in the future I cannot use either method. However, I should be able to write a macro or function in Clojure to automatically generate the C wrapper functions and write them to a file during compilation instead of writing them manually, and make GraalVM include an object file with the compiled functions in the executable.

**Comment by harold** [comment]
@emassey0135 - if you don't mind me asking, what are you building?

This thread is reminding me of https://www.cocotron.org/ ... which ~10yrs ago we used to make a cross-platform desktop app in [Clozure CL](https://ccl.clozure.com/).

**Comment by emassey0135** [comment]
I am trying to create a digital circuit simulator with a graphical user interface that is accessible with screen readers, easy to use, customizable, and capable of being used for a wide range of purposes. A few years ago, I took a Digital Electronics class in high school, and I could not use the circuit simulator the class was using because it was very visual, and I am blind so I use screen readers to interact with computers using the keyboard, speech output, and often braille input and output using a braille display. The only accessible circuit simulator I could find was SPICE, but it seemed very complex and hard to use for the simple digital circuits I was trying to simulate. However, I remembered the digital circuit simulator in The Structure and Interpretation of Computer Programs, and it seemed to be the perfect solution, so I copied the code from that section from the book and added a lot of features to it, including the ability to create truth tables, a module system to replicate breadboard modules and make it easy to connect them, and a syntax for boolean expressions that was automatically transformed into simulated gates. I interacted with my system by adding Scheme source code that specified my circuits, and using a browser-based REPL, and its output was either simple Scheme values or HTML tables added into the document.

For this project, I translated my code from before from Scheme into Clojure, since Clojure seems to have a lot more choices for user interface frameworks, and has good compilers for more platforms than Scheme does. I am trying to write a GUI program that exposes all the features of my simulator, while still being accessible with screen readers, and hopefully being useful for sighted people as well. I will probably add more features to my simulator over time, too. I want it to run on iOS, Android, Windows, MacOS, Linux, and the web, with the best user interface design for each platform, especially differentiating between desktop and mobile.

I initially planned to use ClojureScript with React Native, but I found out that it does not have good desktop support (especially on Linux), and the actual simulation would be slower because it would have to run in Javascript. Electron has the same performance downside, and I would rather not render my UI on desktop using a webpage, because navigating web content with a screen reader is very different than navigating a desktop program, and, at least for web apps, usually more dificult. Clojure CLR with Xamarin, MAUI, or Uno would probably have less performance also, and do not support Linux on the same level as other operating systems. I tried using Flutter with [ClojureDart](https://github.com/tensegritics/clojuredart), but I found out that Flutter lacks some widgets that are important for desktop apps. For example, the closest thing it has to a list box is a scrollable list widget, that does not implement arrow key navigation or keep track of its currently selected item. These behaviors would be dificult to implement properly manually. In addition, there are other things I don't like about the accessibility of some Flutter widgets on desktop. I like the idea of Membrane, but it does not provide any semantic information to the underlying platform, and therefore is completely inaccessible.

So I decided to use each platform's user interface framework directly from Clojure using dtype-next, and create executables for each platform with GraalVM. I plan to use Win32 on Windows, GTK on Linux, and Cocoa on MacOS and iOS using the C aPI for the Objective C runtime. On Android, I will not need GraalVM or dtype-next, since Android already uses Java for all its APIs. For the web, I will use ClojureScript, and maybe one of the React frameworks, and I will also create a PWA. I have other platforms in mind too, such as a command-line program and an HTTP API using AWS Lambda.

**Comment by harold** [comment]
That's just great! Thank you for the clear explanation. Cross-platform desktop productivity tools are always challenging- I certainly wish you the best. Keep up updated w/ your progress, sounds like a very interesting project.

Warm regards.

**Comment by cnuernber** [comment]
@emassey0135 - have you had any success with truffle native interface?  How is this project going?

**Comment by emassey0135** [comment]
Unfortunately, it seems that the Truffle Native Function Interface will not be a good fit for my project. Since it uses Libffi, it probably uses Libffi closures for creating the callbacks it passes to C functions, which generate code at runtime, and runtime code generation is not possible on iOS because of Apple's restrictions, which is also why JIT doesn't work on iOS. Since I plan to add iOS support to my project in the future, and I will need a lot of callbacks for Objective C classes, I would rather find a single approach for callbacks that works on iOS as well as other platforms, and it seems like any approach for generating function pointers that can be passed to C from something else at runtime needs some kind of runtime code generation. Also, I cannot find any way to get the Truffle Native Function Interface to generate a function pointer that I can pass to dtype-next, since it seems that the only time it converts Truffle executable objects, which can encapsulate functions in Java or Truffle languages, to C function pointers is when you pass one to a C function using this interface. So I would probably have to define some C functions using the Truffle interface and some using dtype-next, since dtype-next probably has higher performance and the Truffle function interface lacks some features such as structs. In addition, this means it would be dificult to put a callback pointer into a struct, and there might be more issues with making these frameworks interact well.

So I plan to write a Clojure function to generate C code at compilation time for wrapper functions that call functions generated by expose-clojure-functions and pass a GraalVM isolate to them, and C code to inform Clojure about the addresses of these wrapper functions. I found out that you can make GraalVM generate object files instead of a dynamic library, and I should be able to link these with my C wrapper functions and a C main function that just calls a Clojure main function exposed by expose-clojure-functions, so I could still generate a single executable without an unnecessary library file. I am currently trying to figure out how to create a dynamic library with expose-clojure-functions and call it from C, and I am currently having an issue with invoking other Clojure functions from the one that gets called from C; I am getting undefined variable errors. I have not gotten to the C code generation stage yet.

**Comment by phronmophobic** [comment]
> Never mind, I found out that Libffi closures are not supported on iOS because Apple does not allow code generation at runtime

@emassey0135 , What's the source for this? Is this explicitly disallowed? Is there an instance of someone having their app rejected for this reason?

The reason I ask is that my impression is that people are already using libffi on iOS (maybe not closures?). I also think I've seen other embedded languages like luajit. It's been a while since I've looked into it, but I thought as long as you were using it for code that is shipped with the app and you're not using it to circumvent the app store review process, then it's ok.

**Comment by cnuernber** [comment]
Closing this for now - we haven't figured out how to do this via the TNFI or the graal native FFI system.  You can I believe use JNA from graal native if you unpack the shared library somewhere and link with it specifically.
