### ISSUE TITLE
rolling window left position: the docstring is a bit different from the behaviour

### ISSUE THREAD

**Issue by daslu** [cnuernber/dtype-next#6]
Many thanks for the rolling namespace!
It is so useful in our explorations.

There is a small gap between the behavior (which seems correct) and the documentation.

Let us try:
```clj
$ clj -Sdeps '{:deps {cnuernber/dtype-next {:mvn/version "6.00-beta-9"}}}'
Clojure 1.10.1
user=> (require '[tech.v3.datatype.rolling :as rolling] '[tech.v3.datatype.functional :as dfn])
nil
user=> (rolling/fixed-rolling-window (range 20) 5 dfn/sum {:relative-window-position :left})
[0 1 3 6 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85]
```

On the other hand, the docstring says:
```clj
user> (rolling/fixed-rolling-window (range 20) 5 dfn/sum {:relative-window-position :left})
[0 0 1 3 6 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80]
```

**Comment by daslu** [comment]
https://github.com/cnuernber/dtype-next/blob/e94ed582451d1f045db2512913e0345f1dfa7b1d/src/tech/v3/datatype/rolling.clj#L131

**Comment by cnuernber** [comment]
The behavior is right as of an earlier bug.  Thank you for finding the error in the docstring :-).
