### ISSUE TITLE
dtype-next provides config for nippy

### ISSUE THREAD

**Issue by borkdude** [cnuernber/dtype-next#67]
Hi @cnuernber! 

Thanks for providing a clj-kondo config for your library users, much appreciated. I found one peculiarity today in someone's project:

<img width="635" alt="Screenshot 2022-10-20 at 20 12 21" src="https://user-images.githubusercontent.com/284934/197026348-64033362-6cb7-4ce1-9fad-fb36719b87c6.png">

In this particular case I stumbled upon an issue in someone's project and it was hard to track down where this came from since I didn't expect dtype next to provide a clj-kondo configuration for nippy.

Libraries should probably not provide configuration for other libraries that they don't own.

Thanks again,

Michiel

**Comment by borkdude** [comment]
@cnuernber In particular this construct caused the "unused value", since `type` is a "pure" function:

https://github.com/cnuernber/dtype-next/blob/f16f66fa6b266d29a9908a04109049f1e3c77bd6/resources/clj-kondo.exports/cnuernber/dtype-next/taoensso/nippy.clj#L9

The `dt` argument could probably also be ignored, right?

**Comment by cnuernber** [comment]
Both points I think are valid - the type there was a debug helper that didn't get fully removed.  That being said I myself don't use any kondo-based tools so I have not been maintaining or testing this integration and no one else has stepped up to do so so I think there are two options really - fix just this with a PR or remove it.

**Comment by borkdude** [comment]
I think we can move the nippy config here:

https://github.com/clj-kondo/configs

which is a repo to host configs for third party libraries via dependencies that people can include in their deps.edn.

I'll add it over there and you can remove (only the nippy!) config here.

**Comment by cnuernber** [comment]
Great!  Will do.

**Comment by borkdude** [comment]
Added the config: https://github.com/clj-kondo/configs/tree/main/configs/com.taoensso/nippy

**Comment by cnuernber** [comment]
That config is gone from this project :-)
