### ISSUE TITLE
implement PrimitiveList backed up by mmaped file

### ISSUE THREAD

**Issue by behrica** [cnuernber/dtype-next#7]
As discussed here:
https://github.com/techascent/tech.ml.dataset/issues/190

I will have a look at this, maybe I can implement myself.

**Comment by behrica** [comment]
I have a very primite partial implementation of such a PrimitiveList.

I will make a WIP PR, so you can see the code.

This goes definitely to the edge of my Clojure knowledge, so any advise is welcome.

**Comment by cnuernber** [comment]
I think so far it is fine.  I would like the output stream to be cached and then potentially closed and the mmap handle to be cached.

The mmap handle will auto-close when it falls out of GC scope so we don't need to worry about closing it.

Aside from that, I don't see anything wrong with this.  It should work fine.  It is an encoded string list :-).

**Comment by behrica** [comment]
I benchmarked to keep the output-stream opened,
it saves roughly 20 %.

Keeping the mmap handle only works, if somehow we could guaranty that we first write and then read.


In the general scenario of alternates of `addObject` and `readObject` it does not work.
Maybe a "dirty" flag could help, to detect when to re-obtain the mmap handle.

**Comment by cnuernber** [comment]
Closing for now.
