### ISSUE TITLE
`argops/arggroup` returns a non-functional map 😉

### ISSUE THREAD

**Issue by harold** [cnuernber/dtype-next#74]
https://github.com/cnuernber/dtype-next/blob/7735b40fb501eb4ca6ab28b85d22c994cb9c8d14/src/tech/v3/datatype/argops.clj#L588

```clojure
> (def slot->idx (tech.v3.datatype.argops/arggroup [1 2 3 1 2 3]))
#'slot->idx
> slot->idx
{1 [0 3], 2 [1 4], 3 [2 5]}
```

Nice

```clojure
> (get slot->idx 1)
[0 3]
```
Also nice, but...

```clojure
> (slot->idx 1)
Execution error (ClassCastException) at eval42636 (form-init17704197184208595750.clj:126).
class java.util.LinkedHashMap cannot be cast to class clojure.lang.IFn (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; clojure.lang.IFn is in unnamed module of loader 'app')
```

---

Not a big deal, obviously, because can just call `get`. Caught me out for a second though, because hit this in a heavily threaded context that was swallowing errors.

**Comment by cnuernber** [comment]
Hmm - you are right.  That cannot be the default.

**Comment by cnuernber** [comment]
The approach I want to try is to have a wrapper of Map that makes it functional.

**Comment by harold** [comment]
I’m in favor of that. I had a similar thought but didn’t know the best approach. Interested to see what you come up with.
