### ISSUE TITLE
Tensor printing does not work if some dimensions have size zero and others size > 1

### ISSUE THREAD

**Issue by Cortys** [cnuernber/dtype-next#78]
The `tensor->string` function throws exceptions in some cases.

So far I could identify two slightly different failure scenarios.

## Scenario 1

For tensors where the first i dimensions have size 1 (for i >= 0), followed by one dimension of size zero, followed by some dimensions of size > 1; i.e., shapes of the form `[1* 0 (>1)+]`

Example:
```clojure
(require '[tech.v3.tensor :as dtt])
;; Working examples:
(str (dtt/new-tensor [0])) ;; => "#tech.v3.tensor<float64>[0]\n[]"
(str (dtt/new-tensor [0 1])) ;; => "#tech.v3.tensor<float64>[0 1]\n[]"
(str (dtt/new-tensor [1 0])) ;; => "#tech.v3.tensor<float64>[1 0]\n[]"
(str (dtt/new-tensor [0 1 1])) ;; => "#tech.v3.tensor<float64>[0 1 1]\n[]"

;; Failing cases:
(str (dtt/new-tensor [0 2]))
;; Throws:
; Execution error (IndexOutOfBoundsException) at ham_fisted.ChunkedList/sublistCheck (ChunkedList.java:217).
; End index out of range: end-index(-1), n-elems(0)
(str (dtt/new-tensor [0 2 1])) ;; Also throws. Same message.
(str (dtt/new-tensor [0 1 2])) ;; Also throws. Same message.
(str (dtt/new-tensor [1 0 2])) ;; Also throws. Same message.
(str (dtt/new-tensor [1 1 0 2])) ;; Also throws. Same message.
```

As far as I can tell, the error is caused by [this](https://github.com/cnuernber/dtype-next/blob/d35086951721c887c6c231fb519b4d1392a07654/src/tech/v3/tensor/pprint.clj#L28) `select` call in `column-lengths`.
Maybe, independent from the printing problem, it would be nice if `dtype-proto/select` was able to handle selections into empty tensors without throwing.

## Scenario 2

If there is a size > 1 dimension followed by a size 0 dimension, the print function throws even earlier. 

Example:
```clojure
(str (dtt/new-tensor [2 0]))
;; Throws:
; Execution error at tech.v3.datatype.base/sub-buffer (base.clj:285).
; Offset 0 + length (1) out of range of item length 0
(str (dtt/new-tensor [2 0 1])) ;; Also throws.
(str (dtt/new-tensor [1 2 0])) ;; Also throws.
```

Here, [this](https://github.com/cnuernber/dtype-next/blob/d35086951721c887c6c231fb519b4d1392a07654/src/tech/v3/tensor/pprint.clj#L149) `select` call throws.

**Comment by cnuernber** [comment]
This is a great issue - thanks.

My initial thought is that creating tensors with a dimension of 0 should be an exception upon creation.

Also the error should be clearer not just an out of bounds exception.

How do you see 0 length tensors working?

**Comment by Cortys** [comment]
Coming from numpy, I would intuitively expect empty tensors to be "a thing", for the same reasons that empty lists and empty vectors can be useful in certain scenarios.

As to how they should work in detail, one could copy numpy's approach.
Here are 10 examples showcasing the numpy API for empty arrays:
```python
a = np.zeros((10, 0, 10))

# Working examples:
a.shape # => 1. (10,0,10)
a[2].shape # => 2. (0,10)
a[2,:].shape # => 3. (0,10) Selecting "everything" from an empty dimension works
a[2,::-1].shape # => 4. (0,10) Selecting in reverse also works
a[2, 123:456] # => 5. (0,10) Actually, all slices into an empty dim are ok
a[2,:,4].shape # => 6. (0,)
a[2:4,:,6:9].shape # => 7. (2,0,3)

# Throwing examples:
a[2,0].shape # 8. IndexError: index 0 is out of bounds for axis 1 with size 0
a[10].shape # 9. IndexError: index 10 is out of bounds for axis 0 with size 10
a[0,:,10].shape # 10. IndexError: index 10 is out of bounds for axis 2 with size 10
```

I find this API to be fairly intuitive (maybe apart from example 5, where one can argue whether it should throw or not).
Translating the numpy API to dtype could look something like this:
```clojure
(require '[tech.v3.datatype :as dtype]
         '[tech.v3.tensor :as dtt])

(def a (dtt/new-tensor [10 0 10])

;; Non-throwing examples that already work as they do in numpy:
(dtype/shape a) ; => 1. [0 10 0]
(dtype/shape (dtt/select a 2)) ; => 2. [0 10]
(dtype/shape (dtt/select a 2 :all)) ; => 3. [0 10]

;; Examples that throw in dtype but do not throw in numpy:
(dtype/shape (dtt/select a 2 :lla)) ; 4. Throws
; Execution error (ClassCastException) at tech.v3.datatype.index-algebra/select (index_algebra.clj:242).
; class ham_fisted.Ranges$LongRange cannot be cast to class tech.v3.datatype.ECount (ham_fisted.Ranges$LongRange and tech.v3.datatype.ECount are in unnamed module of loader 'app')

(dtype/shape (dtt/select a 2 (range 123 456))) ; 5. Throws
; Execution error at tech.v3.datatype.monotonic-range/eval37762$fn (monotonic_range.clj:62).
; select-ranges - [0 1 0] [123 1 333] - righthand side out of range

(dtype/shape (dtt/select a 2 :all 4)) ; 6. Throws
; Execution error (IndexOutOfBoundsException) at ham_fisted.ChunkedList/sublistCheck (ChunkedList.java:213).
; Start index out of range: start-index(4), n-elems(0)

(dtype/shape (dtt/select a (range 2 4) :all (range 6 9))) ; 7. Throws
; Execution error at tech.v3.datatype.base/sub-buffer (base.clj:285).
; Offset 6 + length (3) out of range of item length 0

;; Examples that throw in dtype AND in numpy:
(dtype/shape (dtt/select a 2 0)) ; 8. Throws
; Execution error at tech.v3.datatype.index-algebra/select (index_algebra.clj:233).
; Index out of range: 0 >= 0

(dtype/shape (dtt/select a 10)) ; 9. Throws
; Execution error at tech.v3.datatype.index-algebra/select (index_algebra.clj:233).
; Index out of range: 10 >= 10

(dtype/shape (dtt/select a 0 :all 10)) ; 10. Throws
; Execution error at tech.v3.datatype.index-algebra/select (index_algebra.clj:233).
; Index out of range: 10 >= 10
```

As mentioned above, one could argue that dtype's behavior for example 5 is actually ok; I guess it's mostly a matter of personal preference for that case.

Regarding example 4: This should probably go into another issue, but the `:lla` keyword for reverse slicing does not appear to work in general, even for tensors without any 0-dimensions (`(dtt/select (dtt/->tensor (range 10)) :lla)` also throws). Maybe I just misunderstood the [docs](https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/tensor.clj#L361), though.

**Comment by cnuernber** [comment]
This all makes sense and looks good to me - great argument for this not being just an error.  Thanks for the detailed numpy examples!
