### ISSUE TITLE
functional api -- making the main data argument the first

### ISSUE THREAD

**Issue by daslu** [cnuernber/dtype-next#80]
Following [the Zulip conversation](https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/tc.20columns.20and.20dtype-next) that follows @ezmiller's work on the tablecloth column API (branch [ethan/column-api-dev-branch-1](https://github.com/scicloj/tablecloth/tree/ethan/column-api-dev-branch-1)), here are a few functions where we propose reordering the arguments.

The point is to make the main data argument the first so that the functions can be threading-macro-friendly.

@cnuernber [said](https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/tc.20columns.20and.20dtype-next/near/359471353): 

> I think reordering arguments is the most interesting of these.  We can reorder arguments any time a function doesn't take a varying number of primary arguments and we should do so such that the `->` operator takes precedence.  My original thought was that in general in clojure sequence arguments go last but I think this reasoning is only valid when there are potentially multiple sequences - the `+` operator or something like that.

Proposed changes:
* `cummax cummin cumprod cumsum`: make `data` first.
* `kendalls-correlation pearsons-correlation spearmans-correlation`: move `lhs rhs` before `options` 
* `descriptive-statistics`: make `rdr` or `src-rdr` first.
* `percentiles quartiles`: make `data` first

**Comment by openvest** [comment]
is the `->` threading ability to be consistent with some other uses.  I would have expected the `->>` to be more in line with the processing flows for collections (e.g. (->> something (map filter-or-other-func) ...)`  

But maybe that's a row-major vs columnar bias I'm showing.

**Comment by daslu** [comment]
For reference, here is [an old Zulip discussion](https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/argument.20location.20conventions) of the `->` vs `->>` dilemma.

Once nice thing about threading macros is that `->>` can be nested inside `->`, so it is not so bad to handle datasets/tensors/buffers as first arguments but sequences as second arguments.

```clj
(require '[tech.v3.datatype :as dtype]
         '[tech.v3.datatype.functional :as fun])

(-> (dtype/make-reader :float32 100 (rand))
    (->> (filter #(> % 0.99)))
    dtype/->array
    (fun/* 10))

;; => [9.999570024615146 9.935718674352279]
```
