### ISSUE TITLE
replacing & args with options maps

### ISSUE THREAD

**Issue by daslu** [cnuernber/dtype-next#82]
Following the recent [Zulip conversation about the tensor api](https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/tensor.20api), this issue is proposing to generally prefer `options` maps over a variable number of arguments (`& args`).

Except for making things more consistent, having a single argument may arguably make things more composable (when passing around options maps, etc.).

This applies to a few functions at the `tech.v3.datatype.functional` and `tech.v3.tensor` namespaces, and probably a few others.

@harold [said](https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/tensor.20api/near/359479470):
> Agree here that a single options map is preferable to varargs. There _may_ be some reason why varargs are necessary in some case, but probably not, and making this more consistent is a good idea.

**Comment by cnuernber** [comment]
Could we get a list of functions here so we don't miss one when we do the work?

**Comment by daslu** [comment]
I'll look and create a list :+1:

**Comment by daslu** [comment]
Reviewing the cases above, here are the ones where varargs are used to pass optional arguments of some kind:

|                            :ns |                      :name |                                                                     :arglist |
|--------------------------------|----------------------------|------------------------------------------------------------------------------|
|           tech.v3.datatype.ffi |                  c->string |                                                          [data & [encoding]] |
|           tech.v3.datatype.ffi |   define-foreign-interface |                                         [rettype argtypes & [{:as options}]] |
|           tech.v3.datatype.ffi |   define-library-interface | [fn-defs                                                                     |
|                                |                            |  &                                                                           |
|                                |                            |  {:keys [_classname check-error symbols libraries _header-files], :as opts}] |
|           tech.v3.datatype.ffi |                  string->c |                               [str-data & [{:keys [encoding], :as options}]] |
|    tech.v3.datatype.functional |        quartile-outlier-fn |                                                                [item & args] |
|      tech.v3.datatype.gradient |                     diff1d |                                                           [data & [options]] |
|       tech.v3.datatype.jvm-map |                   foreach! |                                                      [item op & [parallel?]] |
|    tech.v3.datatype.statistics |        quartile-outlier-fn |                                                        [item & [range-mult]] |
|    tech.v3.libs.buffered-image |            as-ubyte-tensor |                                                             [img & _options] |
|    tech.v3.libs.buffered-image |        downsample-bilinear |              [src-img & {:keys [dst-img-width dst-img-height dst-img-type]}] |
|    tech.v3.libs.buffered-image |                draw-image! | [src-img                                                                     |
|                                |                            |  dst-image                                                                   |
|                                |                            |  &                                                                           |
|                                |                            |  {:keys                                                                      |
|                                |                            |   [src-x-offset                                                              |
|                                |                            |    src-y-offset                                                              |
|                                |                            |    src-rect-width                                                            |
|                                |                            |    src-rect-height                                                           |
|                                |                            |    dst-x-offset                                                              |
|                                |                            |    dst-y-offset                                                              |
|                                |                            |    dst-rect-width                                                            |
|                                |                            |    dst-rect-height                                                           |
|                                |                            |    interpolation-type]}]                                                     |
|    tech.v3.parallel.queue-iter |                   queue-fn |                                                         [src-fn & [options]] |
|    tech.v3.parallel.queue-iter |                 queue-iter |                                                           [iter & [options]] |
|                 tech.v3.tensor |                      ->jvm |                                                                [item & args] |
|                 tech.v3.tensor |                   ->tensor |                                                                [data & args] |
|                 tech.v3.tensor |                      clone |                                                                [tens & args] |
|                 tech.v3.tensor |           construct-tensor |                                                   [buffer dimensions & args] |
|                 tech.v3.tensor |                 new-tensor |                                                               [shape & args] |
|                 tech.v3.tensor |                     select |                                                                   [t & args] |
| tech.v3.tensor.color-gradients |                   colorize | [src-tens                                                                    |
|                                |                            |  gradient-name                                                               |
|                                |                            |  &                                                                           |
|                                |                            |  {:keys                                                                      |
|                                |                            |   [data-min                                                                  |
|                                |                            |    data-max                                                                  |
|                                |                            |    alpha?                                                                    |
|                                |                            |    check-invalid?                                                            |
|                                |                            |    invert-gradient?                                                          |
|                                |                            |    gradient-default-n],                                                      |
|                                |                            |   :or {gradient-default-n 200}}]                                             |
| tech.v3.tensor.color-gradients |              colorize->clj |                                           [src-tens gradient-name & options] |

**Comment by cnuernber** [comment]
Filtering this further to exclude functions that do in fact take option maps as an optional argument but are destructuring it (which is a performance issue but not what we are fixing here) in the declaration.

* c->string
* quartile-outlier-fn
* foreach!
* as-ubyte-tensor
* downsample-bilinear
* draw-image!
* ->jvm
* ->tensor
* clone
* construct-tensor
* colorize
* colorize->clj


I noticed also that there are namespaces that should be removed as they didn't provide useful.

* locker - failed to perform as expected.
* jvm-map - nearly completely superceded by ham-fisted.
* queue-iter - doesn't provide enough value to keep.

My strategy is going to make the project as correct as possible and either not add deprecated namespaces or do so only when someone really complains as they are actually difficult to do correctly and increase the code size of the finished library.

**Comment by cnuernber** [comment]
Fixed in [changelist #](https://github.com/cnuernber/dtype-next/commit/7798026c171b239180e2adba6d5efd3851dd1cd6)

**Comment by Cortys** [comment]
Sorry to post on an already closed issue, but I just saw the recent commit for this and was wondering whether a breaking change is necessary here.

Since Clojure 1.11 functions with keyword varargs [accept a single options map in addition to the non-wrapped notation](https://clojure.org/news/2021/03/18/apis-serving-people-and-programs), the current dtype API should therefore already support both invokation patterns for most functions:
```clojure
(require '[tech.v3.tensor :as dtt])
(dtt/new-tensor [10 10] :datatype :int8) ; Works
(dtt/new-tensor [10 10] {:datatype :int8}) ; Also already works (using Clojure >= 1.11)
```
By using `(fn [& {:keys [...]}])` over `(fn [& [{:keys [...]}]])` everywhere, both invokation patterns would be supported with fewer breaking changes.

**Comment by cnuernber** [comment]
This is a very good point - I think worth it to try first.
