### ISSUE TITLE
Small typo in docstring

### ISSUE THREAD

**Issue by phronmophobic** [cnuernber/dtype-next#89]
https://github.com/cnuernber/dtype-next/blob/2fc364569634c37f99d399a7f58c99a7a9c0cae2/src/tech/v3/datatype/ffi.clj#L72

I think "syste" should be "system"?

I saw that pass-by-value structs got merged in and was curious what the implementation looked like. Looks great!

**Comment by cnuernber** [comment]
Thanks - I realized after the fact that this is pass-by-value in defining the library itself but *not* when defining a callback (define-foreign-interface).  We will also need that soon-ish so that will be coming if I can get it done with JNA.
