### ISSUE TITLE
tensor to BufferedImage function

### ISSUE THREAD

**Issue by daslu** [cnuernber/dtype-next#92]
[link to Zulip topic](https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/tensor.20to.20image)

Often, when working with images, I find it useful to convert them to dtype-next tensors using `tech.v3.libs.buffered-image/as-ubyte-tensor`, then process them as tensors, then convert them back to images.

To convert back tensors to images, some helper function is usually handy, something like the following (thanks to @harold's adaptation).
```clj
(require '[tech.v3.libs.buffered-image :as bufimg]
         '[tech.v3.datatype :as dtype]
         '[tech.v3.tensor :as tensor]
         '[tech.v3.datatype.functional :as fun])

(defn tensor->image
  [tensor img-type]
  (let [[h w] (dtype/shape tensor)
        new-img (bufimg/new-image h w img-type)]
    (dtype/copy! tensor
                 (tensor/ensure-tensor new-img))
    new-img))
```

An image processing example using tensors:

```clj
(def raw-image
  (bufimg/load "https://upload.wikimedia.org/wikipedia/commons/1/1e/Gay_head_cliffs_MV.JPG"))

raw-image
```

![image](https://github.com/cnuernber/dtype-next/assets/5673102/88d346d3-bc5f-4060-813c-f1e7318212dc)

```clj
(-> raw-image   
    bufimg/as-ubyte-tensor
    (fun/* 0.3) ;; make it a bit darker
    (tensor->image :byte-bgr))
```

![image](https://github.com/cnuernber/dtype-next/assets/5673102/7d65f4c5-f99f-4d40-967e-51ae03630954)

Would it make sense to add such a `tensor->image` function to dtype-next?

(I added it to another library (the WIP [Noj](https://github.com/scicloj/noj) library), but then realized it should probably belong to dtype-next.)

**Comment by harold** [comment]
I think this is quite cool - definitely similar things strewn about that could use this.

After thinking a bit more today nice documentation (and possibly a nice default value?) for the type parameter might be nice.

**Comment by harold** [comment]
@cnuernber - in case you missed this. (:

**Comment by cnuernber** [comment]
I think this is great - I think it should go into the libs/buffered-image namespace as that has all the constants involved.  There could be default constants for 1 channel, 3 channel, and 4 channel tensors respectively.

Related to this is [colorizing tensors](https://cnuernber.github.io/dtype-next/tech.v3.tensor.color-gradients.html#var-colorize).
