### ISSUE TITLE
Error when using reduce-axis and tech.v3.tensor/select

### ISSUE THREAD

**Issue by benjamin-asdf** [cnuernber/dtype-next#94]
Hi, 

```
;; cnuernber/dtype-next {:mvn/version "10.111"}

(ns repro
  (:require [tech.v3.tensor :as dtt]
            [tech.v3.datatype.functional :as dtype-fn]))

(do
  (def n-neurons 1000)

  (def weights (dtt/clone (dtt/compute-tensor [n-neurons n-neurons] (fn [_ _] (< (rand) 0.1)) :boolean)))

  (def activations (dtt/->tensor (range n-neurons)))

  (dtt/reduce-axis (dtt/select weights (dtt/->tensor (range 1000))) dtype-fn/sum 0 :float32))
;; 1. Caused by java.lang.NullPointerException
;;    Cannot invoke "java.lang.Number.doubleValue()" because "x" is null

;;                    RT.java: 1282  clojure.lang.RT/longCast
;;                   base.clj:  285  tech.v3.datatype.base/sub-buffer
;;                   base.clj:  282  tech.v3.datatype.base/sub-buffer
;;             tensor_api.clj:  218  tech.v3.tensor-api/eval18332/fn/reify
;;                Buffer.java:  172  tech.v3.datatype.Buffer/reduce
;;                   core.clj: 6907  clojure.core/reduce
;;                   core.clj: 6890  clojure.core/reduce
;;               unary_op.clj:  274  tech.v3.datatype.unary-op/eval15406/fn/reify
;;                   core.clj: 6907  clojure.core/reduce
;;                   core.clj: 6992  clojure.core/mapv
;;                   core.clj: 6992  clojure.core/mapv
;;                 pprint.clj:   35  tech.v3.tensor.pprint/column-lengths
;;                 pprint.clj:   19  tech.v3.tensor.pprint/column-lengths
;;                 pprint.clj:  156  tech.v3.tensor.pprint/base-tensor->string
;;                 pprint.clj:  118  tech.v3.tensor.pprint/base-tensor->string
;;                 pprint.clj:  122  tech.v3.tensor.pprint/base-tensor->string
;;                 pprint.clj:  118  tech.v3.tensor.pprint/base-tensor->string
;;                 pprint.clj:  167  tech.v3.tensor.pprint/tensor->string
;;                 pprint.clj:  162  tech.v3.tensor.pprint/tensor->string
;;             tensor_api.clj:  453  tech.v3.tensor-api.DirectTensor/toString
;;             tensor_api.clj:  459  tech.v3.tensor-api/eval18438/fn
;;               MultiFn.java:  234  clojure.lang.MultiFn/invoke
;;                 pprint.clj:   40  cider.nrepl.pprint/pr/fn
;;                   AFn.java:  152  clojure.lang.AFn/applyToHelper
;;                   AFn.java:  144  clojure.lang.AFn/applyTo
;;                   core.clj:  667  clojure.core/apply
;;                   core.clj: 1990  clojure.core/with-bindings*
;;                   core.clj: 1990  clojure.core/with-bindings*
;;                RestFn.java:  428  clojure.lang.RestFn/invoke
;;                 pprint.clj:   37  cider.nrepl.pprint/pr
;;                 pprint.clj:   29  cider.nrepl.pprint/pr
;;                   Var.java:  395  clojure.lang.Var/invoke
;;                  print.clj:  224  nrepl.middleware.print/wrap-print/fn/print
;;                  print.clj:  148  nrepl.middleware.print/send-nonstreamed/print-key/fn
;;                  print.clj:  147  nrepl.middleware.print/send-nonstreamed/print-key
;;                   core.clj: 2759  clojure.core/map/fn/fn
;;              protocols.clj:   49  clojure.core.protocols/iter-reduce
;;              protocols.clj:   75  clojure.core.protocols/fn
;;              protocols.clj:   75  clojure.core.protocols/fn
;;              protocols.clj:   13  clojure.core.protocols/fn/G
;;                   core.clj: 6969  clojure.core/transduce
;;                   core.clj: 6955  clojure.core/transduce




;; same issue:

(do
  (def n-neurons 1000)

  (def weights (dtt/clone (dtt/compute-tensor [n-neurons n-neurons] (fn [_ _] (< (rand) 0.1)) :boolean)))
  #_(def activations (dtt/->tensor (range n-neurons)))

  (dtt/reduce-axis (dtt/select weights (into [] (range n-neurons))) dtype-fn/sum 0 :float32))


;; but this works:

(do
  (def n-neurons 1000)

  (def weights (dtt/clone (dtt/compute-tensor [n-neurons n-neurons] (fn [_ _] (< (rand) 0.1)) :boolean)))
  #_(def activations (dtt/->tensor (range n-neurons)))

  (dtt/reduce-axis (dtt/select weights (range n-neurons)) dtype-fn/sum 0 :float32))
```

I suppose that is a bug?

**Comment by cnuernber** [comment]
I need to look at this closer but yes it appears to be a bug -- thanks for letting us know!

**Comment by cnuernber** [comment]
There is a bug here but also an issue with usage - select doesn't need a tensor and in fact is much more efficient with the range object as opposed to `(dtt/->tensor (range 10))`.  Specifically what select knows in the case of a range is that the select arg is monotonically increasing and has a distinct min,max which allows for it to be very precise with the underlying buffer.  

That being said, there is also an issue here where slice assumed tensor object dimension that has a precise buffer ecount which can't happen if a user passes in an arbitrary list of integers (or a tensor) as a select argument.

So great issue - it did expose a real bug.

**Comment by benjamin-asdf** [comment]
Nice to learn about this. My use case I basically want to keep around a set of indices, they are sort of sparse, so some small list of indices. ('neuron activations'). 

Sounds like select is then not the correct interface? The end result should be selecting (small subset) rows and reducing each column to a single number.

**Comment by cnuernber** [comment]
Select is - just the argument to select can be just a range for an optimization that in your case (sort of sparse) can't always be applied.  select itself doesn't require a tensor and your example made one out of a range so my point was just that using the range itself would be more efficient but not I see that it was a simple example not a real use case.  The real use case is I guess a sparse ordered set of indexes.

The argument to select can be anything so an int array is another efficient mechanism.  If you are building up this sort of sparse representation perhaps a [roaring bitmap](https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/datatype/bitmap.clj#L181) - which has an efficient conversion to an [array of integers](https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/datatype/bitmap.clj#L78) - would be an ideal buffer type.  Another thing perhaps to look at when building the representation is the [index-reducer](https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/datatype/unary_pred.clj#L286) which is used in operations such as [argfilter](https://github.com/cnuernber/dtype-next/blob/master/src/tech/v3/datatype/argops.clj#L488).

In any case - I think this latest release of dtype-next will work for you - let us know if it doesn't and reopen this if it is still throwing on slice/select ops.

**Comment by benjamin-asdf** [comment]
many thanks!
