### ISSUE TITLE
emap casting :int32 as long

### ISSUE THREAD

**Issue by rschmukler** [cnuernber/dtype-next#95]
It seems that there is a bug somewhere in `emap` that causes the result to be coerced as a long instead of an int. This trickles up the ecosystem..

Below is a simple way to recreate the issue I am seeing:

```clojure
(-> (dt/emap int :int32 [3 4 5])
      first
      type)
;; => java.lang.Long
```

I noticed that the `cast-fn` var inside the implementation of `emap` is unused but didn't see a quick fix as I am not too familiar with the implementation details.  Any help would be greatly appreciated!

**Comment by cnuernber** [comment]
All integers and unsigned integers are read as long values - this is by design to reduce the number of type special cases - just long and double.
