### ISSUE TITLE
Doc typo

### ISSUE THREAD

**Issue by light-matters** [cnuernber/dtype-next#96]
Just highlighting a typo in the docs:

_This can be used to **crap** an image or to do reorderings such as imagespace bga->rgb conversions._

EDIT:
https://cnuernber.github.io/dtype-next/cheatsheet.html

Sorry, I definitely 'copied' a link to the page, but apparently I just didn't paste it

**Comment by cnuernber** [comment]
Where did you find this?

**Comment by harold** [comment]
https://github.com/cnuernber/dtype-next/blob/ce52aabc4777a085fd389b50490344972c430cb9/topics/cheatsheet.md?plain=1#L202-L204

**Comment by harold** [comment]
Hilariously, such a function can be used (traditionally) to _crop_ an image, but if you really need to _crap_ an image, `select` may still be the function you're looking for.
